SemantixFramework:
- task: "multilabel_classification"
  n_runs: 10
  init_kwargs:
    prompt: "" # No prompt needed for Semantix
    llm_model: "gpt-4o-mini-2024-07-18"
    llm_model_family: "openai"
    retries: 0
    source_data_pickle_path: "data/multilabel_classification.pkl"
- task: "ner"
  n_runs: 10
  init_kwargs:
    prompt: "" # No prompt needed for Semantix
    llm_model: "gpt-4o-mini-2024-07-18"
    llm_model_family: "openai"
    retries: 0
    source_data_pickle_path: "data/ner.pkl"
- task: "synthetic_data_generation"
  n_runs: 100
  init_kwargs:
    prompt: "" # No prompt needed for Semantix
    llm_model: "gpt-4o-mini-2024-07-18"
    llm_model_family: "openai"
    retries: 0

VanillaOpenAIFramework:
  - task: "multilabel_classification"
    n_runs: 10
    init_kwargs:
      prompt: "Classify the following text: {text}"
      llm_model: "gpt-4o-mini-2024-07-18"
      llm_model_family: "openai"
      source_data_pickle_path: "data/multilabel_classification.pkl"
  - task: "ner"
    n_runs: 10
    init_kwargs:
      prompt: "Extract and resolve a list of entities from the following text: {text}"
      llm_model: "gpt-4o-mini-2024-07-18"
      llm_model_family: "openai"
      source_data_pickle_path: "data/ner.pkl"
  - task: "synthetic_data_generation"
    n_runs: 100
    init_kwargs:
      prompt: "Generate a random person's information. The name must be chosen at random. Make it something you wouldn't normally choose."
      llm_model: "gpt-4o-mini-2024-07-18"
      llm_model_family: "openai"

InstructorFramework:
  - task: "multilabel_classification"
    n_runs: 10
    init_kwargs:
      prompt: "Classify the following text: {text}"
      llm_model: "gpt-4o-mini-2024-07-18"
      llm_model_family: "openai"
      retries: 0
      source_data_pickle_path: "data/multilabel_classification.pkl"
  - task: "ner"
    n_runs: 10
    init_kwargs:
      prompt: "Extract and resolve a list of entities from the following text: {text}"
      llm_model: "gpt-4o-mini-2024-07-18"
      llm_model_family: "openai"
      retries: 0
      source_data_pickle_path: "data/ner.pkl"
  - task: "synthetic_data_generation"
    n_runs: 100
    init_kwargs:
      prompt: "Generate a random person's information. The name must be chosen at random. Make it something you wouldn't normally choose."
      llm_model: "gpt-4o-mini-2024-07-18"
      llm_model_family: "openai"
      retries: 0

MarvinFramework:
  - task: "multilabel_classification"
    n_runs: 10
    init_kwargs:
      prompt: "Classify the following text: {text}"
      llm_model: "gpt-4o-mini-2024-07-18"
      llm_model_family: "openai"
      retries: 0 
      source_data_pickle_path: "data/multilabel_classification.pkl"
  - task: "ner"
    n_runs: 10
    init_kwargs:
      prompt: "Extract and resolve a list of entities from the following text: {text}"
      llm_model: "gpt-4o-mini-2024-07-18"
      llm_model_family: "openai"
      retries: 0
      source_data_pickle_path: "data/ner.pkl"
  - task: "synthetic_data_generation"
    n_runs: 100
    init_kwargs:
      prompt: "Generate a random person's information. The name must be chosen at random. Make it something you wouldn't normally choose."
      llm_model: "gpt-4o-mini-2024-07-18"
      llm_model_family: "openai"

FructoseFramework:
  - task: "multilabel_classification"
    n_runs: 10
    init_kwargs:
      prompt: "Classify the following text: {text}"
      llm_model: "gpt-4o-mini-2024-07-18"
      llm_model_family: "openai"
      retries: 0
      source_data_pickle_path: "data/multilabel_classification.pkl"
  - task: "ner"
    n_runs: 10
    init_kwargs:
      prompt: "Extract and resolve a list of entities from the following text: {text}"
      llm_model: "gpt-4o-mini-2024-07-18"
      llm_model_family: "openai"
      retries: 0
      source_data_pickle_path: "data/ner.pkl"

LlamaIndexFramework:
  - task: "multilabel_classification"
    n_runs: 10
    init_kwargs:
      prompt: "Classify the following text: {text}"
      llm_model: "gpt-4o-mini-2024-07-18"
      llm_model_family: "openai"
      retries: 0
      source_data_pickle_path: "data/multilabel_classification.pkl"
  - task: "ner"
    n_runs: 10
    init_kwargs:
      prompt: "Extract and resolve a list of entities from the following text: {text}"
      llm_model: "gpt-4o-mini-2024-07-18"
      llm_model_family: "openai"
      retries: 0
      source_data_pickle_path: "data/ner.pkl"
  - task: "synthetic_data_generation"
    n_runs: 100
    init_kwargs:
      prompt: "Generate a random person's information. The name must be chosen at random. Make it something you wouldn't normally choose."
      llm_model: "gpt-4o-mini-2024-07-18"
      llm_model_family: "openai"

ModelsmithFramework:
  - task: "multilabel_classification"
    n_runs: 10
    init_kwargs:
      prompt: "Classify the following text: {text}"
      llm_model: "gpt-4o-mini-2024-07-18"
      llm_model_family: "openai"
      retries: 0
      source_data_pickle_path: "data/multilabel_classification.pkl"
  - task: "synthetic_data_generation"
    n_runs: 1
    init_kwargs:
      prompt: "Generate a random person's information. The name must be chosen at random. Make it something you wouldn't normally choose."
      llm_model: "gpt-4o-mini-2024-07-18"
      llm_model_family: "openai"
      retries: 0
  - task: "ner"
    n_runs: 10
    init_kwargs:
      prompt: "Extract and resolve a list of entities from the following text: {text}"
      llm_model: "gpt-4o-mini-2024-07-18"
      llm_model_family: "openai"
      retries: 0
      source_data_pickle_path: "data/ner.pkl"

# MirascopeFramework:
#   - task: "multilabel_classification"
#     n_runs: 1
#     init_kwargs:
#       prompt: "Classify the following text: {text}"
#       llm_model: "gpt-4o-mini-2024-07-18"
#       llm_model_family: "openai"
#       retries: 0
#       source_data_pickle_path: "data/multilabel_classification.pkl"
#   - task: "ner"
#     n_runs: 1
#     init_kwargs:
#       prompt: "Extract and resolve a list of entities from the following text: {text}"
#       llm_model: "gpt-4o-mini-2024-07-18"
#       llm_model_family: "openai"
#       retries: 0
#       source_data_pickle_path: "data/ner.pkl"
#   - task: "synthetic_data_generation"
#     n_runs: 1
#     init_kwargs:
#       prompt: "Generate a random person's information. The name must be chosen at random. Make it something you wouldn't normally choose."
#       llm_model: "gpt-4o-mini-2024-07-18"
#       llm_model_family: "openai"
#       retries: 0

# OutlinesFramework:
#   - task: "multilabel_classification"
#     n_runs: 10
#     init_kwargs:
#       prompt: "Classify the following text: {text}"
#       llm_model: "unsloth/llama-3-8b-Instruct-bnb-4bit"
#       llm_model_family: "transformers"
#       retries: 0 # Oulines transformers has no retry parameter
#       source_data_pickle_path: "data/multilabel_classification.pkl"
#   - task: "synthetic_data_generation"
#     n_runs: 100
#     init_kwargs:
#       prompt: "Generate a random person's information. The name must be chosen at random. Make it something you wouldn't normally choose."
#       llm_model: "unsloth/llama-3-8b-Instruct-bnb-4bit"
#       llm_model_family: "transformers"
#   - task: "ner"
#     n_runs: 10
#     init_kwargs:
#       prompt: "Extract and resolve a list of entities from the following text: {text}"
#       llm_model: "unsloth/llama-3-8b-Instruct-bnb-4bit"
#       llm_model_family: "transformers"
#       retries: 0 # Oulines transformers has no retry parameter
#       source_data_pickle_path: "data/ner.pkl"
#

# LMFormatEnforcerFramework:
#   - task: "multilabel_classification"
#     n_runs: 10
#     init_kwargs:
#       prompt: "Classify the following text: {text}.\nRespond in the following json schema: {json_schema}:\n"
#       llm_model: "unsloth/llama-3-8b-Instruct-bnb-4bit"
#       llm_model_family: "transformers"
#       retries: 0 
#       source_data_pickle_path: "data/multilabel_classification.pkl"
#       max_length: 4096
#   - task: "ner"
#     n_runs: 10
#     init_kwargs:
#       prompt: "Extract and resolve a list of entities from the following text: {text}.\nRespond in the following json schema: {json_schema}:\n"
#       llm_model: "unsloth/llama-3-8b-Instruct-bnb-4bit"
#       llm_model_family: "transformers"
#       retries: 0 
#       source_data_pickle_path: "data/ner.pkl"
#       max_length: 4096
#   - task: "synthetic_data_generation"
#     n_runs: 100
#     init_kwargs:
#       prompt: "Generate a random person's information. The name must be chosen at random. Make it something you wouldn't normally choose.\nRespond in the following json schema: {json_schema}:\n"
#       llm_model: "unsloth/llama-3-8b-Instruct-bnb-4bit"
#       llm_model_family: "transformers"
#       max_length: 4096