SemantixFramework:
- init_kwargs:
    llm_model: gpt-4o-mini-2024-07-18
    llm_model_family: openai
    prompt: ''
    retries: 2
    source_data_pickle_path: data/multilabel_classification.pkl
  n_runs: 1
  task: multilabel_classification
- init_kwargs:
    llm_model: gpt-4o-mini-2024-07-18
    llm_model_family: openai
    prompt: ''
    retries: 2
    source_data_pickle_path: data/ner.pkl
  n_runs: 1
  task: ner
- init_kwargs:
    llm_model: gpt-4o-mini-2024-07-18
    llm_model_family: openai
    prompt: ''
    retries: 2
  n_runs: 10
  task: synthetic_data_generation
